# Set variables once
variables:
  configuration: debug
  TEST_IOS_SDK: iphonesimulator11.4
  TEST_IOS_PLATFORM: iOS Simulator
  TEST_IOS_OS: 11.4
  TEST_IOS_DEVICE_NAME: 'iPhone SE'
  IOS_FABRIC_UPLOAD: 1
  ANDROID_FABRIC_UPLOAD: 1
  ESLINT_CHECKS: 0

jobs:
- template: scripts/ci/templates/buildJobs.yml

  
